## 第一题: 计算梯度

$$z = \log \left( \frac{1}{\sum_i \exp(a_i)} \sum_j b_j \right) - \sum_k b_k,$$

给定表达式 \( z \) 及其关于向量 $ \mathbf{a}$ 和 $ \mathbf{b} $ 的梯度的 Python 实现，使用 PyTorch 自动微分功能，并进行验证：

### 1.问题描述
给定：
$$ z = \log \left( \frac{1}{\sum_i \exp(a_i)} \sum_j b_j \right) - \sum_k b_k $$

要求计算：
1. grad_a = $ \frac{\partial z}{\partial \mathbf{a}} $
2. grad_b = $ \frac{\partial z}{\partial \mathbf{b}} $


### 2.可能用到的函数
   • `torch.sum()` `torch.exp()`  `torch.log()`
   
   •定义可微张量`torch.tensor(..., requires_grad=True)`
   
   • 自动计算梯度`.backward()`  存储梯度` .grad` 


### 3.输入

a = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], requires_grad=True)

b = torch.tensor([0.01] * 10, requires_grad=True)

### 4.Python 实现（使用 PyTorch）
你需要：
1. 计算 z
2. 反向传播计算梯度
3. 提取梯度 grad_a ，grad_b

In [1]:

import torch

# 定义输入向量 a 和 b（这里用随机值初始化，实际使用时替换为具体值）
a = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], requires_grad=True)
b = torch.tensor([0.01] * 10, requires_grad=True)
# 计算 z
sum_exp_a = torch.sum(torch.exp(a))
sum_b = torch.sum(b)
z = torch.log(sum_b / sum_exp_a) - sum_b

# 反向传播计算梯度
z.backward()

# 提取梯度
grad_a = a.grad
grad_b = b.grad

print("Gradient wrt a:")
print(grad_a)
print("\nGradient wrt b:")
print(grad_b)

Gradient wrt a:
tensor([-0.0612, -0.0676, -0.0748, -0.0826, -0.0913, -0.1009, -0.1115, -0.1233,
        -0.1362, -0.1505])

Gradient wrt b:
tensor([9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000,
        9.0000])


In [2]:
# 手动验证梯度公式
# 1. 对 a 的梯度 = -softmax(a)
softmax_a = torch.exp(a) / sum_exp_a
grad_a_manual = -softmax_a

# 2. 对 b 的梯度 = 1/sum_b - 1
grad_b_manual = torch.ones_like(b) * (1 / sum_b - 1)

# 打印结果
print("自动微分计算的梯度:")
print("Gradient wrt a:\n", grad_a)
print("Gradient wrt b:\n", grad_b)

print("\n手动公式验证的梯度:")
print("Gradient wrt a (manual):\n", grad_a_manual)
print("Gradient wrt b (manual):\n", grad_b_manual)

# 检查一致性
assert torch.allclose(grad_a, grad_a_manual, atol=1e-4), "a的梯度验证失败!"
assert torch.allclose(grad_b, grad_b_manual, atol=1e-4), "b的梯度验证失败!"
print("\n梯度验证通过!")

自动微分计算的梯度:
Gradient wrt a:
 tensor([-0.0612, -0.0676, -0.0748, -0.0826, -0.0913, -0.1009, -0.1115, -0.1233,
        -0.1362, -0.1505])
Gradient wrt b:
 tensor([9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000,
        9.0000])

手动公式验证的梯度:
Gradient wrt a (manual):
 tensor([-0.0612, -0.0676, -0.0748, -0.0826, -0.0913, -0.1009, -0.1115, -0.1233,
        -0.1362, -0.1505], grad_fn=<NegBackward0>)
Gradient wrt b (manual):
 tensor([9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000, 9.0000,
        9.0000], grad_fn=<MulBackward0>)

梯度验证通过!


## 第一题: 计算梯度

$$z = \log \left( \frac{1}{\sum_i \exp(a_i)} \sum_j b_j \right) - \sum_k b_k,$$

给定表达式 \( z \) 及其关于向量 $ \mathbf{a}$ 和 $ \mathbf{b} $ 的梯度的 Python 实现，使用 PyTorch 自动微分功能，并进行验证：

### 1.问题描述
给定：
$$ z = \log \left( \frac{1}{\sum_i \exp(a_i)} \sum_j b_j \right) - \sum_k b_k $$

要求计算：
1. grad_a = $ \frac{\partial z}{\partial \mathbf{a}} $
2. grad_b = $ \frac{\partial z}{\partial \mathbf{b}} $


### 2.可能用到的函数
   • `torch.sum()` `torch.exp()`  `torch.log()`
   
   •定义可微张量`torch.tensor(..., requires_grad=True)`
   
   • 自动计算梯度`.backward()`  存储梯度` .grad` 


### 3.输入

a = torch.tensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], requires_grad=True)

b = torch.tensor([0.01] * 10, requires_grad=True)

### 4.Python 实现（使用 PyTorch）
你需要：
1. 计算 z
2. 反向传播计算梯度
3. 提取梯度 grad_a ，grad_b

In [ ]:

########################
#                      #
#       test2          #
#                      #
########################
import cv2
import numpy as np
import matplotlib.pyplot as plt


#锐化卷积核
kernel1 = np.array([
    [ 0, -1,  0],
    [-1,  5, -1],
    [ 0, -1,  0]
], dtype=np.float32)

#边缘检测卷积核（垂直边缘）
kernel2 = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
], dtype=np.float32)

#高斯模糊卷积核
kernel3 = np.array([
    [1/16, 2/16, 1/16],
    [2/16, 4/16, 2/16],
    [1/16, 2/16, 1/16]
], dtype=np.float32)
def Filter(kernel,img,row,col): 
    result=0
    # 卷积核的边⻓
    dim=np.array(kernel).shape[0]
    for i in range(dim):
        for c in range(dim):
            result=result+kernel [i][c]*img [i+row][col+c]
    return result
def Conv(kernel,img,res_row,res_col):
    Result = np.zeros((res_row,res_col))
    # 通过调⽤前⾯的Filter函数来对特征图每⼀个位置进⾏卷积操作
    for i in range(res_row):
        for c in range(res_col):
            Result [i][c]=Filter(kernel,img,i,c)
    return Result

# 读取并处理图像
img = cv2.imread('fig1.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
width, height=50, 50
n=1

img_resized = cv2.resize(img, (width, height), interpolation=cv2.INTER_LINEAR)
img_pad = np.pad(img_resized,n, mode='constant')

# 创建2x2的子图布局
plt.figure(figsize=(10, 10))

# 显示填充后的图像
plt.subplot(2, 2, 1)
plt.imshow(img_pad, cmap='gray')
plt.title('Original Image')

# 计算并显示锐化结果
featuremap_pad1 = Conv(kernel1, img_pad, 50, 50)
plt.subplot(2, 2, 2)
plt.imshow(featuremap_pad1, cmap='gray')
plt.title('Sharpened')

# 计算并显示边缘检测结果
featuremap_pad2 = Conv(kernel2, img_pad, 50, 50)
plt.subplot(2, 2, 3)
plt.imshow(featuremap_pad2, cmap='gray')
plt.title('Edge Detection')

# 计算并显示高斯模糊结果
featuremap_pad3 = Conv(kernel3, img_pad, 50, 50)
plt.subplot(2, 2, 4)
plt.imshow(featuremap_pad3, cmap='gray')
plt.title('Gaussian Blur')

# 调整子图间距
plt.tight_layout()

# 显示所有图像
plt.show()

## 第三题: 3.1 Softmax回归实现与手写数字分类

### 1. 问题描述
请完成以下代码，实现一个简单的基于 Softmax 回归的手写数字分类器。你需要补全函数中的关键部分。

### 2. 梯度公式推导
#### (1) 定义模型和损失函数
• **线性得分**（未归一化）：
$$
  \mathbf{s} = \mathbf{X} \mathbf{W}
  $$
  • $ \mathbf{X} $：输入数据矩阵$( N \times D $，$ N $ 是样本数，$ D $ 是特征数）
  • $ \mathbf{W} $：权重矩阵$( D \times C $，$ C $ 是类别数）
  • $ \mathbf{s} $：得分矩阵$( N \times C $）

• **Softmax概率**：
$$
  p_{ij} = \frac{e^{s_{ij}}}{\sum_{k=1}^C e^{s_{ik}}}
  $$
  • $ p_{ij} $：样本 $ i $ 属于类别 $ j $ 的概率

• **交叉熵损失**：
$$
  \mathcal{L} = -\frac{1}{N} \sum_{i=1}^N \sum_{j=1}^C y_{ij} \log p_{ij}
  $$
  • $ y_{ij} $：真实标签的one-hot编码$( y_{ij} = 1 $ 如果样本 $ i $ 属于类别 $ j $，否则 $ 0 $）

#### (2) 计算梯度
• **损失对得分 $ \mathbf{s} $ 的梯度**：
$$
  \frac{\partial \mathcal{L}}{\partial s_{ij}} = p_{ij} - y_{ij}
  $$
  • 解释：
    ◦ 如果 $ y_{ij} = 1 $，梯度 $ p_{ij} - 1 $（鼓励模型增加正确类别的概率）
    ◦ 如果 $ y_{ij} = 0 $，梯度 $ p_{ij} $（鼓励模型减少错误类别的概率）

• **损失对权重 $ \mathbf{W} $ 的梯度**：
$$
  \frac{\partial \mathcal{L}}{\partial \mathbf{W}} = \frac{1}{N} \mathbf{X}^T (\mathbf{P} - \mathbf{Y})
  $$
  • $ \mathbf{P} $：预测概率矩阵$( N \times C $）
  • $ \mathbf{Y} $：真实标签的one-hot矩阵$( N \times C $）

#### (3) 梯度更新
• **梯度下降更新规则**：
$$
  \mathbf{W} \leftarrow \mathbf{W} - \eta \frac{\partial \mathcal{L}}{\partial \mathbf{W}}
  $$
  • $ \eta $：学习率（控制更新步长）

---


### 3.公式总结
| 公式 | 含义 |
|------|------|
| $$ \mathbf{s} = \mathbf{X} \mathbf{W} $$ | 计算线性得分 |
| $ p_{ij} = \text{softmax}(s_{ij}) $ | 计算概率分布 |
| $ \mathcal{L} = -\frac{1}{N} \sum y_{ij} \log p_{ij} $ | 计算交叉熵损失 |
| $ \frac{\partial \mathcal{L}}{\partial \mathbf{W}} = \frac{1}{N} \mathbf{X}^T (\mathbf{P} - \mathbf{Y}) $ | 计算梯度 |
| $ \mathbf{W} \leftarrow \mathbf{W} - \eta \frac{\partial \mathcal{L}}{\partial \mathbf{W}} $ | 更新权重 |

### 4.可能用到的函数
   • `矩阵乘法运算符@或np.dot()` 
   
   • `使用np.log()计算对数` 
   
   • `使用matrix_T=matrix.T  或 np.transpose(matrix)对nparray求转置`
   
   • `np.sum(a, axis=None, keepdims=False)`
   
    ### **参数说明**
    | 参数 | 说明 |
    |------|------|
    | `a` | 输入数组（可以是 NumPy 数组或类似数组的结构） |
    | `axis` | 指定求和的轴（默认 `None`，表示对所有元素求和） |
    | `keepdims` | 是否保持原数组的维度（默认 `False`，求和后降维） |
    • `axis=0`：对**列**求和（跨行计算）
    • `axis=1`：对**行**求和（跨列计算）
    • `keepdims=True` 可以保持求和后的维度不变，避免降维。
        # 默认 keepdims=False（降维）
        sum_cols = np.sum(arr, axis=0)
        print(sum_cols.shape)  # 输出 (2,)（降维）
        # 使用 keepdims=True（保持维度）， 在 `softmax` 计算中，保持维度以便正确广播：
        x = np.array([[1, 2], [3, 4]])
        x_sum = np.sum(x, axis=1, keepdims=True)  # 保持 (2,1) 形状

| 功能 | 代码示例 |
|------|---------|
| 对整个数组求和 | `np.sum(arr)` |
| 沿行求和 | `np.sum(arr, axis=1)` |
| 沿列求和 | `np.sum(arr, axis=0)` |
| 保持维度 | `np.sum(arr, axis=1, keepdims=True)` |


###  5. 预期输出

loss 下降，Test Accuracy >= 0.9

###  6.Python 实现
你需要：

补全1: softmax值

` 
    # 提示1: 先对x进行数值稳定处理(减去最大值)
    # 提示2: 计算每个元素的指数
    # 提示3: 对每行的指数值进行归一化(除以`__行__`总和)，`__保持维度__`
`     


补全2: 计算得分scores

` 
    # 提示1: 得分是输入数据X_train与权重矩阵W的线性组合
    # 提示2:使用矩阵乘法运算符@或np.dot()
    # 提示3: scores.shape=(1437, 10)
`   

补全3: 计算损失loss

` 
    # 提示1: 交叉熵损失公式: -sum(y_true * log(y_pred+1e-8)) / N
    # 提示2: 使用np.log()计算对数
    # 提示3: 使用np.sum()求和
    # 提示4: （加 `1e-8` 避免 `log(0)`）
` 

补全4: 计算梯度

` 
    # 提示:已经给出答案
` 

补全5: 更新权重

` 
    # 提示1: 更新权重公式
    # 提示2: grad.shape= (64, 10)
` 

In [23]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

def softmax(x):
    """计算输入x的softmax函数"""
    x_exp = np.exp(x - np.max(x, axis=1, keepdims=True))
    return x_exp / np.sum(x_exp, axis=1, keepdims=True)

def train_softmax(X_train, y_train, num_classes, learning_rate=0.01, epochs=100):
    N, D = X_train.shape
    C = num_classes
#     print('N, D,C', N, D,C)
    # 初始化权重矩阵
    W = np.random.randn(D, C) * 0.01
    
    # 将标签转换为one-hot编码
    y_one_hot = np.zeros((N, C))
    y_one_hot[np.arange(N), y_train] = 1
    
    for epoch in range(epochs):
        # 前向传播
        scores = X_train @ W  # 补全1: 计算得分
#         print('scores.shape',scores.shape)
        probs = softmax(scores)
#         print('probs.shape',probs.shape)
        
        # 计算损失 (交叉熵损失)
        loss = -np.sum(y_one_hot * np.log(probs+1e-8)) / N  # 补全2: 计算损失
#         print('loss.shape',loss.shape)
        # 反向传播
        grad = X_train.T @ (probs - y_one_hot) / N  # 补全3: 计算梯度
#         print('grad.shape',grad.shape)
        # 更新权重
        W -= learning_rate * grad
        
        if epoch % 10 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    
    return W

# 加载数据
digits = load_digits()
X = digits.data
y = digits.target

# 数据预处理
X = X / 16.0  # 归一化到0-1范围

# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 训练模型
W = train_softmax(X_train, y_train, num_classes=10, learning_rate=0.2, epochs=200)

# 测试模型
scores_test = X_test @ W
predicted_classes = np.argmax(scores_test, axis=1)
accuracy = np.mean(predicted_classes == y_test)
print(f"Test Accuracy: {accuracy:.4f}")

Epoch 0, Loss: 2.2966
Epoch 10, Loss: 1.9393
Epoch 20, Loss: 1.6566
Epoch 30, Loss: 1.4337
Epoch 40, Loss: 1.2585
Epoch 50, Loss: 1.1200
Epoch 60, Loss: 1.0094
Epoch 70, Loss: 0.9199
Epoch 80, Loss: 0.8465
Epoch 90, Loss: 0.7855
Epoch 100, Loss: 0.7341
Epoch 110, Loss: 0.6903
Epoch 120, Loss: 0.6525
Epoch 130, Loss: 0.6197
Epoch 140, Loss: 0.5909
Epoch 150, Loss: 0.5654
Epoch 160, Loss: 0.5426
Epoch 170, Loss: 0.5222
Epoch 180, Loss: 0.5038
Epoch 190, Loss: 0.4871
Test Accuracy: 0.9139


## 拓展：Softmax回归实现与手写数字分类（小批量SGD版本）

### 1. 问题描述
请完成以下代码，实现一个基于 **小批量随机梯度下降（Mini-batch SGD）** 优化的 Softmax 回归手写数字分类器。你需要补全函数中的关键部分，并使用 **Mini-batch SGD** 进行权重更新。

### 2. 梯度公式推导
（与批量梯度下降相同，但每次仅使用 **1个样本** 计算梯度）


| 公式 | 含义 |
|------|------|
| $$ \mathbf{S} = \mathbf{X}_{batch} \mathbf{W} $$ | 计算小批量样本的线性得分矩阵 |
| $ P_{ij} = \text{softmax}(S_{ij}) $ | 计算小批量样本的概率分布矩阵 |
| $ \mathcal{L} = -\frac{1}{B}\sum_{i=1}^B \sum_{j=1}^C Y_{ij} \log P_{ij} $ | 计算小批量样本的平均交叉熵损失 |
| $ \frac{\partial \mathcal{L}}{\partial \mathbf{W}} = \frac{1}{B} \mathbf{X}_{batch}^T (\mathbf{P} - \mathbf{Y}) $ | 计算小批量样本的平均梯度 |
| $ \mathbf{W} \leftarrow \mathbf{W} - \eta \frac{\partial \mathcal{L}}{\partial \mathbf{W}} $ | 使用平均梯度更新权重 |

#### 维度说明

• $\mathbf{X}_{batch}$: 小批量样本矩阵 (B×D)
• $\mathbf{W}$: 权重矩阵 (D×C)
• $\mathbf{S}$, $\mathbf{P}$, $\mathbf{Y}$: 得分/概率/标签矩阵 (B×C)
• $B$: batch_size
• $C$: 类别数
• $D$: 特征维度
`

### 3. 预期输出
• Loss 应逐渐下降。

• Test Accuracy >= 0.95

### 4. 关键区别（批量梯度下降 vs SGD vs 小批量SGD）

| **特性**               | **批量梯度下降 (BGD)**                     | **随机梯度下降 (SGD)**                     | **小批量梯度下降 (Mini-batch SGD)**       |
|------------------------|------------------------------------------|------------------------------------------|------------------------------------------|
| **梯度计算方式**        | 使用**全部训练样本**计算梯度              | 使用**单个样本**计算梯度                  | 使用**小批量样本**（如32、64个）计算梯度  |
| **梯度公式**            | $\frac{1}{N} \mathbf{X}^T (\mathbf{P} - \mathbf{Y})$ | $\mathbf{x}_i^T (\mathbf{p}_i - \mathbf{y}_i)$ | $\frac{1}{B} \mathbf{X}_{\text{batch}}^T (\mathbf{P}_{\text{batch}} - \mathbf{Y}_{\text{batch}})$ |
| **更新频率**            | 每轮（epoch）**1次**更新                  | 每样本**1次**更新                         | 每小批量**1次**更新                      |
| **内存占用**            | 高（需存储全部样本的梯度）                | 低（仅需当前样本的梯度）                  | 中等（取决于batch_size）                 |
| **收敛速度**            | 稳定但慢                                 | 快但震荡大                               | 较快且较稳定                             |
| **适用场景**            | 小数据集（<1万样本）                     | 大数据集或在线学习                       | 通用（最常用）                           |                     |

` 
   • $B$ 表示batch_size
   • $\mathbf{X}_{\text{batch}}$ 是小批量数据矩阵（B×D）
   • $\mathbf{P}_{\text{batch}}$ 是小批量预测概率（B×C）
   • $\mathbf{Y}_{\text{batch}}$ 是小批量真实标签（B×C）
 ` 
#### 特点
1. 当 B=1 时退化为标准SGD
2. 当 B=N 时退化为批量梯度下降
3. 实际使用时通常取 B=32/64/128 等值

### 5.补充说明：
batch_size：

实际使用时通常取 B=32/64/128 等值（小批量SGD）：平衡速度和稳定性。
当 B=N 时退化为批量梯度下降：稳定但计算量大。
当 B=1 时退化为标准SGD，（纯SGD）：收敛快但噪声大。

learning_rate：

SGD通常需要更小的学习率（如 0.01~0.1)

###  6.Python 实现
你需要：

补全1: softmax值

` 
    # 提示1: 先对x进行数值稳定处理(减去最大值) - 已在前一行完成
    # 提示2: 计算每个元素的指数 - 已在exp_x = np.exp(x_stable)完成
    # 提示3: 对每行的指数值进行归一化(除以行总和)，保持维度
`     


补全2: 计算得分scores

` 
    # 提示1: 得分是输入数据X_batch与权重矩阵W的线性组合
    # 提示2: 使用矩阵乘法运算符@或np.dot()
    # 提示3: scores.shape=(batch_size, 10)
`   

补全3: 计算损失loss

` 
    # 提示1: 交叉熵损失公式: ` $\mathcal{L} = -\frac{1}{B}\sum_{i=1}^B \sum_{j=1}^C Y_{ij} \log P_{ij} $

`   
    # 提示2: 使用np.log()计算对数
    # 提示3: 使用np.sum()求和，可使用np.mean()求均值，也可不使用
    # 提示4: （加1e-8避免log(0)）
` 

补全4: 计算梯度

` 
    # 提示1:计算梯度
    # 提示2: 转置
` 

补全5: 更新权重

` 
    # 提示1: 更新权重公式
    # 提示2: grad.shape= (64, 10)
` 

In [20]:

import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

def softmax(x):
    """计算输入x的softmax函数"""
    x_stable = x - np.max(x, axis=1, keepdims=True)  # 数值稳定性处理
    exp_x = np.exp(x_stable)
    softmax_prob = exp_x / np.sum(exp_x, axis=1, keepdims=True)  # 补全1: softmax值
    return softmax_prob

def train_softmax_Mini_batch_sgd(X_train, y_train, num_classes, learning_rate=0.01, epochs=100):
    """
    训练Softmax回归模型（使用SGD优化）
    """
    N, D = X_train.shape  # (1437 ,64)
    C = num_classes  # 10
    
    # 初始化权重矩阵
    W = np.random.randn(D, C) * 0.01
    
    # 将标签转换为one-hot编码
    y_one_hot = np.zeros((N, C))
    y_one_hot[np.arange(N), y_train] = 1
    
    for epoch in range(epochs):
        # 随机打乱数据
        indices = np.random.permutation(N)
        X_shuffled = X_train[indices]
        y_shuffled = y_train[indices]
        y_one_hot_shuffled = y_one_hot[indices]
        
        # 小批量梯度下降（Mini-batch SGD）
        batch_size = 32
        for i in range(0, N, batch_size):
            X_batch = X_shuffled[i:i+batch_size]
            y_batch = y_one_hot_shuffled[i:i+batch_size]
            
            # 前向传播
            scores = X_batch @ W  # 补全2: 计算得分 (batch_size, 10)
            probs = softmax(scores)
            
            # 计算损失（仅用于监控）
            loss = -np.mean(np.sum(y_batch * np.log(probs + 1e-8), axis=1))  # 补全3: 计算单个样本的损失
            #loss = -np.sum(y_batch * np.log(probs + 1e-8))  # 直接对所有样本和类别求和
            #loss = -np.sum(np.sum(y_batch * np.log(probs + 1e-8), axis=1))  # 先按样本求和，再全局求和
            # 反向传播，计算梯度
            grad = (X_batch.T @ (probs - y_batch)) / batch_size  # 补全4: 计算梯度 (64, 10)
#             print('grad.shape',grad.shape)
            # 更新权重
            W = W - learning_rate * grad  # 补全5: 更新权重
        
        # 每10轮打印一次整个训练集的损失
        if epoch % 10 == 0:
            scores_full = X_train @ W
            probs_full = softmax(scores_full)
            full_loss = -np.mean(np.sum(y_one_hot * np.log(probs_full + 1e-8), axis=1))
            print(f"Epoch {epoch}, Loss: {full_loss:.4f}")
    
    return W

# 加载数据
digits = load_digits()
X = digits.data
y = digits.target

# 数据预处理
X = X / 16.0  # 归一化到0-1范围

# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 训练模型（使用Mini-batch SGD）
W = train_softmax_Mini_batch_sgd(X_train, y_train, num_classes=10, learning_rate=0.2, epochs=200)

# 测试模型
scores_test = X_test @ W
predicted_classes = np.argmax(scores_test, axis=1)
accuracy = np.mean(predicted_classes == y_test)
print(f"Test Accuracy: {accuracy:.4f}")


Epoch 0, Loss: 1.2022
Epoch 10, Loss: 0.2799
Epoch 20, Loss: 0.2004
Epoch 30, Loss: 0.1658
Epoch 40, Loss: 0.1452
Epoch 50, Loss: 0.1309
Epoch 60, Loss: 0.1206
Epoch 70, Loss: 0.1118
Epoch 80, Loss: 0.1049
Epoch 90, Loss: 0.0994
Epoch 100, Loss: 0.0941
Epoch 110, Loss: 0.0897
Epoch 120, Loss: 0.0860
Epoch 130, Loss: 0.0823
Epoch 140, Loss: 0.0792
Epoch 150, Loss: 0.0764
Epoch 160, Loss: 0.0739
Epoch 170, Loss: 0.0714
Epoch 180, Loss: 0.0692
Epoch 190, Loss: 0.0672
Test Accuracy: 0.9722
